"""Bounded, authenticated voucher PDFs; no public voucher URLs."""
from decimal import Decimal
from io import BytesIO
from pathlib import Path
import threading
from xml.sax.saxutils import escape
from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,KeepTogether
from django.utils import timezone
from .models import Account,Item,Voucher,AuditEvent
from .views import api,owned_id
from django.http import HttpResponse

FONT_LOCK=threading.Lock()
GREEN=colors.HexColor('#245c43')


def text(value):return escape(str(value or '')).replace('\n','<br/>')

def amount(value):
    whole,fraction=f'{Decimal(str(value or 0)):.2f}'.split('.')
    sign='-' if whole.startswith('-') else ''
    digits=whole.lstrip('-');tail=digits[-3:];head=digits[:-3];groups=[]
    while head:groups.insert(0,head[-2:]);head=head[:-2]
    return sign+'₹'+','.join([*groups,tail])+'.'+fraction


def voucher_pdf_bytes(workspace,voucher,user):
    with FONT_LOCK:
        if 'NotoSans' not in pdfmetrics.getRegisteredFontNames():pdfmetrics.registerFont(TTFont('NotoSans',str(Path(__file__).parent/'fonts/NotoSans-Regular.ttf')))
    styles={name:ParagraphStyle(name,fontName='NotoSans',fontSize=size,leading=size*1.5,textColor=colors.HexColor('#20382e'),spaceAfter=6) for name,size in [('body',9),('small',8),('title',22),('section',11)]}
    styles['right']=ParagraphStyle('right',parent=styles['body'],alignment=TA_RIGHT)
    def p(value,style='body'):return Paragraph(text(value),styles[style])
    def table(headers,rows,widths):
        data=[[p(h,'small') for h in headers]]+[[p(cell,'right' if i>0 and headers[i] in ('Quantity','Rate','Amount','Debit','Credit','Value') else 'body') for i,cell in enumerate(row)] for row in rows]
        result=Table(data,colWidths=widths,repeatRows=1,hAlign='LEFT')
        result.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#eaf0e5')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7),('LINEBELOW',(0,0),(-1,0),.7,GREEN),('LINEBELOW',(0,1),(-1,-1),.3,colors.HexColor('#e1e6dd'))]))
        return result
    output=BytesIO();width=174*mm
    doc=SimpleDocTemplate(output,pagesize=(210*mm,297*mm),rightMargin=18*mm,leftMargin=18*mm,topMargin=18*mm,bottomMargin=23*mm,title=f'{voucher.number} - {workspace.name}',author=workspace.name)
    d=voucher.data
    account_ids=[value for value in [d.get('account'),d.get('cash_account')] if value]+[r['account'] for r in d.get('balances',[])]
    item_ids=[r['item'] for r in d.get('lines',[])]
    accounts={str(a.id):a.name for a in Account.objects.filter(workspace=workspace,id__in=account_ids)}
    items={str(i.id):i.name for i in Item.objects.filter(workspace=workspace,id__in=item_ids)}
    story=[p(workspace.name,'title')]
    contact=[workspace.address,', '.join(x for x in [workspace.city,workspace.postcode] if x), ' | '.join(x for x in [workspace.mobile,workspace.email] if x)]
    story.extend(p(value,'small') for value in contact if value)
    story.extend([Spacer(1,6*mm),p(voucher.get_kind_display(),'section'),table(['Voucher','Date','Status'],[[voucher.number,voucher.date.strftime('%d %b %Y'),'Reversed' if Voucher.objects.filter(reverses=voucher).exists() else 'Posted']],[width*.38,width*.30,width*.32]),Spacer(1,5*mm)])
    if d.get('account'):story.append(p('Account: '+accounts.get(d['account'],'Account')))
    if d.get('cash_account'):story.append(p('Cash / bank: '+accounts.get(d['cash_account'],'Account')))
    reference=d.get('reference') or str(voucher.reverses_id or '')
    if reference:
        source=Voucher.objects.filter(workspace=workspace,pk=reference).first()
        if source:story.append(p('Reference: '+source.number))
    if d.get('lines'):
        rows=[[items.get(l['item'],'Item'),l['quantity'],amount(l['rate']) if l.get('rate') else '-',amount(l['amount'])] for l in d['lines']]
        story.extend([Spacer(1,3*mm),table(['Item','Quantity','Rate','Amount'],rows,[width*.46,width*.16,width*.18,width*.20])])
    if d.get('balances'):
        story.extend([Spacer(1,3*mm),table(['Account','Side','Amount'],[[accounts.get(r['account'],'Account'),r['side'].title(),amount(r['amount'])] for r in d['balances']],[width*.55,width*.20,width*.25])])
    story.extend([Spacer(1,5*mm),table(['Voucher total','Amount'],[['INR',amount(d['amount'])]],[width*.70,width*.30])])
    if d.get('narration'):story.extend([Spacer(1,4*mm),p('Narration','section'),p(d['narration'])])
    generated=timezone.localtime(timezone.now()).strftime('%d %b %Y %H:%M %Z')
    story.extend([Spacer(1,5*mm),p('Generated by '+user.username+' | '+generated,'small'),p('Voucher ID: '+str(voucher.id),'small')])
    def footer(canvas,document):
        canvas.saveState();canvas.setStrokeColor(GREEN);canvas.line(18*mm,17*mm,192*mm,17*mm);canvas.setFont('NotoSans',8);canvas.setFillColor(colors.HexColor('#68766e'));canvas.drawString(18*mm,12*mm,'Simple Books | INR | '+workspace.timezone);canvas.drawRightString(192*mm,12*mm,f'Page {document.page}');canvas.restoreState()
    doc.build(story,onFirstPage=footer,onLaterPages=footer)
    return output.getvalue()


@api()
def voucher_pdf(request,voucher_id):
    voucher=owned_id(voucher_id,Voucher,request.workspace,'voucher')
    content=voucher_pdf_bytes(request.workspace,voucher,request.user)
    AuditEvent.objects.create(workspace=request.workspace,actor=request.user,action='voucher.pdf_exported',details={'voucher':str(voucher.id),'number':voucher.number,'version':voucher.version})
    response=HttpResponse(content,content_type='application/pdf')
    response['Content-Disposition']=f'attachment; filename="{voucher.number}.pdf"'
    return response
