# Generated by Django 5.2.18 on 2026-10-07 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='books.calculationrun')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('PAY', 'Payment'), ('REC', 'Receipt'), ('SAL', 'Sales'), ('PUR', 'Purchase'), ('CN', 'Credit note'), ('DN', 'Debit note'), ('REV', 'Reversal')], max_length=3)),
                ('sequence', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='books.voucher')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('fingerprint', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.voucher')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='calculationrun',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace'),
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('expense', 'Expense'), ('income', 'Income'), ('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity')], max_length=15)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('balance_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.item')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.calculationrun')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'item', 'date'], name='books_stock_run_id_ea6b60_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_quantity__gte', 0), ('balance_value__gte', 0)), name='nonnegative_stock')],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.account')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.calculationrun')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.voucher')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'account', 'date'], name='books_journ_run_id_e186ab_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='one_journal_side')],
            },
        ),
        migrations.CreateModel(
            name='VoucherRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='books.voucher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('voucher', 'version'), name='revision_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['workspace', 'date', 'created_at'], name='books_vouch_workspa_7a2fee_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(fields=('workspace', 'kind', 'sequence'), name='voucher_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['PAY', 'REC', 'SAL', 'PUR', 'CN', 'DN', 'REV'])), name='valid_voucher_kind'),
        ),
        migrations.AddConstraint(
            model_name='mutation',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='item_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='account_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='account_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['cash', 'bank', 'customer', 'supplier', 'expense', 'income', 'asset', 'liability', 'equity'])), name='valid_account_kind'),
        ),
    ]
