# Generated by Django 5.2.18 on 2026-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_append_only_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='voucher',
            name='valid_voucher_kind',
        ),
        migrations.AlterField(
            model_name='voucher',
            name='kind',
            field=models.CharField(choices=[('PAY', 'Payment'), ('REC', 'Receipt'), ('SAL', 'Sales'), ('PUR', 'Purchase'), ('CN', 'Credit note'), ('DN', 'Debit note'), ('REV', 'Reversal'), ('OPN', 'Opening balances')], max_length=3),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['PAY', 'REC', 'SAL', 'PUR', 'CN', 'DN', 'REV', 'OPN'])), name='valid_voucher_kind'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'OPN')), fields=('workspace',), name='one_opening_per_workspace'),
        ),
    ]
