# Generated by Django 5.2.18 on 2026-10-08 07:34

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta

def initialise_subscriptions(apps,schema_editor):
    Workspace=apps.get_model("books","Workspace")
    Subscription=apps.get_model("books","Subscription")
    today=timezone.localdate()
    for workspace in Workspace.objects.all().iterator():
        Subscription.objects.create(workspace=workspace,starts_on=today,expires_on=today+timedelta(days=30),notes="Existing development workspace")



class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='address',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='workspace',
            name='city',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workspace',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='postcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='workspace',
            name='profile_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_days__gte', 1), ('price__gte', 0)), name='valid_plan_terms')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='trial', max_length=12)),
                ('starts_on', models.DateField()),
                ('expires_on', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='books.workspace')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='books.subscriptionplan')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['trial', 'active', 'suspended'])), name='valid_subscription_status'), models.CheckConstraint(condition=models.Q(('expires_on__gte', models.F('starts_on'))), name='valid_subscription_period')],
            },
        ),
        migrations.RunPython(initialise_subscriptions,migrations.RunPython.noop),
    ]
