# Generated by Django 5.2.18 on 2026-10-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_workspace_address_workspace_city_workspace_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'verbose_name': 'Customer company', 'verbose_name_plural': 'Customer companies'},
        ),
    ]
