# Generated by Django 5.2.18 on 2026-10-09 05:54

import django.db.models.deletion
from django.db import migrations, models
from books.sqlite_integrity import install, uninstall


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_subscription_activated_at_subscription_key_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_key', models.TextField()),
                ('last_seen_date', models.DateField()),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='books.workspace')),
            ],
        ),
        migrations.RunPython(install, uninstall),
    ]
